spring:
  mail:
    username: eglrgroup9@gmail.com
    password: z5i59QRJLwpAyxT
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
application:
  serverURL: localhost:8080
  jwt:
    jwtSecret: that_depends_a_good_deal_on_where_you_want_to_get_to_then_it_doesnt_much_matter_which_way_you_go
    jwtExpirationMs: 1800000
    jwtHeader: Authorization
    jwtHeaderStart: Bearer
