#server:
#  port: 8200
spring:
  application:
    name: warehouse
  security:
    user:
      name: warehouse-service
      password: warehouse-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: warehouseservice
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 5
#  client:
#    service-url:
#      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}