version: '2'
volumes:
  mongodb_server_data:
services:
  eureka-server:
    image: thepassengerhub/eureka:0.1
    container_name: eureka-server
    ports:
      - 8761:8761
  mongo:
    image: mongo
    container_name: mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    ports:
      - 27017:27017 
    volumes:
      - mongodb_server_data:/data/db
  catalog-service:
    image: thepassengerhub/catalog-service:0.1
    container_name: catalog-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - mongo
    links:
      - eureka-server
      - mongo
    env_file:
      - ./catalogservice.env
  order-service:
    image: thepassengerhub/order-service:0.1
    container_name: order-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
      - catalog-service
      - redis
    links:
      - eureka-server
      - kafka
      - mongo
      - catalog-service
      - redis
    env_file:
      - ./orderservice.env
  wallet-service:
    image: thepassengerhub/wallet-service:0.1
    container_name: wallet-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
    links:
      - eureka-server
      - kafka
      - mongo
    env_file:
      - ./walletservice.env
  warehouse-service:
    image: thepassengerhub/warehouse-service:0.1
    container_name: warehouse-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
      - catalog-service
    links:
      - eureka-server
      - kafka
      - mongo
      - catalog-service
    env_file:
      - ./warehouseservice.env
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  connect:
    image: thepassengerhub/debezium:0.1
    container_name: kafka_connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
    links:
      - kafka
      - zookeeper
      - mongo
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

networks:
  default:
    name: ecommerce-network
