server:
  port: 8100
spring:
  application:
    name: wallet
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: walletDB
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

