server:
  port: 8100
spring:
  application:
    name: wallet
#  security:
#    user:
#      name: wallet-service
#      password: wallet-service
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: walletservice
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
application:
  jwt:
    jwtSecret: that_depends_a_good_deal_on_where_you_want_to_get_to_then_it_doesnt_much_matter_which_way_you_go
    jwtExpirationMs: 1800000

